name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name:  ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Update APT
      shell: bash
      run: sudo apt-get update

    - name: Install Emacs
      shell: bash
      run : sudo apt-get install emacs

    - name: Build
      shell: bash
      run: make

    - name: Run Tests
      shell: bash
      run: make test
